### ISSUE TITLE
Difference with respect to BorderlessMaximizedWindows

### ISSUE THREAD

**Issue by D3vil0p3r** [fin444/truely-maximized#3]
What are the differences between truely-maximized and the built-in `BorderlessMaximizedWindows`?

**Comment by fin444** [comment]
The first difference is I didn't realize that setting even existed 😄

If you install Truely Maximized and don't configure it, there should (from what I can tell) be 0 difference between the two, with the exception that #1 does not occur in Plasma's implementation. However, this script adds configuration options to blacklist certain applications, and to [add a screen edge listener that will show the title bar if you need it](https://camo.githubusercontent.com/f2732c97863da3691af5b10ac520bf0f9bdd5978b8d2ebb898fe10f2542a2ac7/68747470733a2f2f696d616765732e706c696e672e636f6d2f696d672f30302f30302f37312f33362f38342f323031383537332f766964656f2e676966) (though you can [create a similar workaround in Plasma](https://discuss.kde.org/t/hide-titlebars-of-maximised-windows/1162/7)).

**Comment by xiota** [comment]
@fin444 I don't use this plugin/script.  However, I'd suggest modifying it into a front-end to manage/extend the built-in `BorderlessMaximizedWindows` option.

Some other programs/widgets also attempt to manage the option.  Would also be good to attempt to detect such plugins so that the user can be notified of potential conflicts.  Even if you opt not to alter the option, programs that do so could still interfere with the function of your script.
